CREATE TABLE posts(
id INT auto_increment,
user_id INT,
title VARCHAR(100),
body TEXT,
publish_date DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id),
FOREIGN KEY(user_id) REFERENCES users(id)
);

# CREATES TABLE WITH FOREGIN KEY REFERENCE and publish_date DEFAULT CURRENT_TIMESTAMP